# Generated by Django 5.0.14 on 2026-04-09 03:16

from django.db import migrations
from decimal import Decimal

def seed_toronto_parking(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    ParkingSpot = apps.get_model("parkings", "ParkingSpot")

    toronto_addresses = [
        "55 Front St W, Toronto, ON M5J 1E6",
        "3 King St E, Toronto, ON M5H 1A1",
        "8 Queen St W, Toronto, ON M5C 1X7",
        "3 Carlton St., Toronto, ON M5B 1L2",
        "1 Dundas St E, Toronto, ON M5B 2R8",
    ]

    rates = [Decimal("4.00"), Decimal("4.50"), Decimal("3.75"), Decimal("5.00"), Decimal("4.25")]

    for address, rate in zip(toronto_addresses, rates):
        location = Location.objects.filter(address=address).first()
        if not location:
            continue
        ParkingSpot.objects.get_or_create(
            location=location,
            rate=rate,
            defaults={"is_available": True},
        )


def reverse_toronto_parking(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    ParkingSpot = apps.get_model("parkings", "ParkingSpot")

    toronto_addresses = [
        "55 Front St W, Toronto, ON M5J 1E6",
        "3 King St E, Toronto, ON M5H 1A1",
        "8 Queen St W, Toronto, ON M5C 1X7",
        "3 Carlton St., Toronto, ON M5B 1L2",
        "1 Dundas St E, Toronto, ON M5B 2R8",
    ]

    locations = Location.objects.filter(address__in=toronto_addresses)
    ParkingSpot.objects.filter(location__in=locations).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("parkings", "0003_reservation_window_and_seed_availability"),
        ("core", "0005_seed_locations"),
    ]

    operations = [
        migrations.RunPython(seed_toronto_parking, reverse_toronto_parking),
    ]
