# Generated by Django 5.0.14 on 2026-03-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rentablevehicle_location_rentalstation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentablevehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented-out', 'Rented-Out'), ('out-of-service', 'Out-Of-Service')], default='available', max_length=20),
        ),
    ]
