# Generated by Django 5.0.14 on 2026-03-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rentablevehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalstation',
            name='type',
            field=models.CharField(choices=[('car', 'Car'), ('escooter', 'EScooter'), ('bike', 'Bike')], default='bike', max_length=20),
        ),
    ]
