# Generated by Django 5.0.14 on 2026-03-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rentablevehicle_status_rental_status_and_more'),
        ('rentals', '0004_rentalstation_type'),
    ]

    operations = [
    ]
