# Generated by Django 5.0.14 on 2026-03-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'CUSTOMER'), ('operator', 'OPERATOR'), ('admin', 'ADMIN')], default='customer', max_length=20),
        ),
    ]
