# Generated by Django 5.0.14 on 2026-04-09 00:48
from decimal import Decimal
from django.db import migrations


def seed_toronto(apps, schema_editor):
    City = apps.get_model("core", "City")
    Location = apps.get_model("core", "Location")

    toronto, _ = City.objects.get_or_create(
        name="Toronto",
        defaults={
            "top_left_x":     Decimal("44.000000"),
            "top_left_y":     Decimal("-79.700000"),
            "top_right_x":    Decimal("44.000000"),
            "top_right_y":    Decimal("-79.000000"),
            "bottom_left_x":  Decimal("43.500000"),
            "bottom_left_y":  Decimal("-79.700000"),
            "bottom_right_x": Decimal("43.500000"),
            "bottom_right_y": Decimal("-79.000000"),
        },
    )

    locations_seed = [
        ("55 Front St W, Toronto, ON M5J 1E6",          Decimal("43.645419"), Decimal("-79.380748")),
        ("3 King St E, Toronto, ON M5H 1A1",            Decimal("43.649079"), Decimal("-79.377955")),
        ("8 Queen St W, Toronto, ON M5C 1X7",           Decimal("43.652397"), Decimal("-79.379229")),
        ("3 Carlton St., Toronto, ON M5B 1L2",          Decimal("43.661315"), Decimal("-79.383101")),
        ("1 Dundas St E, Toronto, ON M5B 2R8",          Decimal("43.656228"), Decimal("-79.380715")),
        ("2 Bloor St, Toronto, ON M4W 1A8",             Decimal("43.670931"), Decimal("-79.385854")),
        ("1407 Yonge St, Toronto, ON M4T 1Y7",          Decimal("43.687311"), Decimal("-79.393461")),
        ("80 Queens Park, Toronto, ON M5S 2C5",         Decimal("43.666861"), Decimal("-79.394621")),
        ("750 Spadina Ave., Toronto, ON M5S 2J2",       Decimal("43.666531"), Decimal("-79.403934")),
        ("1300 Eglinton Ave E, Toronto, ON M3C 0C7",    Decimal("43.699335"), Decimal("-79.436111")),
        ("25 Vitti St, North York, ON M3K 1Z9",         Decimal("43.753507"), Decimal("-79.478938")),
        ("100 New Park Pl, Vaughan, ON P0J 1C0",        Decimal("43.796156"), Decimal("-79.528008")),
        ("6301 Silver Dart Dr, Mississauga, ON L5P 1B2",Decimal("43.684256"), Decimal("-79.615613")),
        ("941 Progress Ave, Scarborough, ON M1G 3T8",   Decimal("43.785199"), Decimal("-79.228249")),
        ("2455 Eglinton Ave E, Scarborough, ON M1K 3N7",Decimal("43.732354"), Decimal("-79.264088")),
        ("1800 Sheppard Ave E, Toronto, ON M2J 5A7",    Decimal("43.777827"), Decimal("-79.344705")),
        ("49 Karl Fraser Rd, North York, ON M3C 0E5",   Decimal("43.736598"), Decimal("-79.344698")),
    ]

    for address, x, y in locations_seed:
        Location.objects.get_or_create(
            address=address,
            defaults={"x": x, "y": y, "city": toronto},
        )


def reverse_toronto(apps, schema_editor):
    City = apps.get_model("core", "City")
    Location = apps.get_model("core", "Location")
    toronto = City.objects.filter(name="Toronto").first()
    if toronto:
        Location.objects.filter(city=toronto).delete()
        toronto.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_seed_demo_data'),
    ]
    operations = [
        migrations.RunPython(seed_toronto, reverse_toronto),
    ]